---
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32: WINNT_x86-gcc3
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 4.5-alpha-3
versions:
    4.5-alpha-3:
        platformVersion: 31.4.0
        detailsURL: https://www.torproject.org/projects/torbrowser.html.en
        download_url: https://www.torproject.org/dist/torbrowser/4.5-alpha-3
        incremental_from:
          - 4.5-alpha-2
        migrate_archs:
          osx32: osx64
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
