---
download:
    archive_url: https://archive.torproject.org/tor-package-archive/torbrowser
    gpg_keyring: ../../gitian/gpg/torbrowser.gpg
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32: WINNT_x86-gcc3
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 5.5a6
    release: 5.0
versions:
    5.0:
        platformVersion: 38.2.0
        detailsURL: https://www.torproject.org/projects/torbrowser.html.en
        download_url: https://www.torproject.org/dist/torbrowser/5.0
        incremental_from:
          - 4.5.3
        migrate_archs:
          osx32: osx64
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
    5.5a6:
        platformVersion: 38.5.0
        detailsURL: https://blog.torproject.org/blog/tor-browser-55a6-released
        download_url: https://www.torproject.org/dist/torbrowser/5.5a6
        incremental_from:
          - 5.5a5
        migrate_archs:
          osx32: osx64
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
