---
appname_marfile: tor-browser
appname_bundle_osx: TorBrowser
appname_bundle_linux: tor-browser
appname_bundle_win: torbrowser-install
releases_dir: ../../gitian
download:
    archive_url: https://archive.torproject.org/tor-package-archive/torbrowser
    gpg_keyring: ../../gitian/gpg/torbrowser.gpg
    bundles_url: https://dist.torproject.org/torbrowser
    mars_url: https://cdn.torproject.org/aus1/torbrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 6.5a6
    release: 6.0.1
versions:
    6.0.1:
        platformVersion: 45.2.0
        detailsURL: https://blog.torproject.org/blog/tor-browser-601-released
        incremental_from:
          - 5.5.5
          - 6.0
        migrate_archs:
          osx32: osx64
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
    6.5a6:
        platformVersion: 45.6.0
        detailsURL: https://blog.torproject.org/blog/tor-browser-65a6-released
        incremental_from:
          - 6.5a4
          - 6.5a5
        migrate_archs:
          osx32: osx64
        migrate_langs:
            pt-PT: pt-BR
        osx32:
            minSupportedOSVersion: 10.8
            detailsURL: https://blog.torproject.org/blog/end-life-plan-tor-browser-32-bit-macs#updating
